server:
  port: 8181
spring:
  redis:
    host: localhost
    port: 6379
    client-type: jedis
    jedis:
      pool:
        max-active: 16
    timeout: 10000
  mail:
    host: smtp.qq.com
    username: 1933848966@qq.com
    password: nolcdvvovjuqcdhh
    default-encoding: UTF-8
  datasource:
    username: root
    password: ly
    url: jdbc:mysql://127.0.0.1:3306/zncq_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  banner:
    location: banner.text

mybatis:
  mapper-locations: classpath:**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.igeek.zncq.entity
pagehelper:
  helper-dialect: mysql
  params:
    count: countSql
  reasonable: true
  support-methods-arguments: true


